apiVersion: v1
kind: Pod
metadata:
  labels:
    ci: minos-api-build
spec:
  containers:
  - name: dind
    image: 196229073436.dkr.ecr.eu-west-1.amazonaws.com/oa-infrastructure/dind
    securityContext:
      privileged: true
  - name: musl
    image: 196229073436.dkr.ecr.eu-west-1.amazonaws.com/openanalytics/rust-musl-minos
    tty: true
    resources:
      requests:
        memory: "2Gi"
      limits:
        memory: "4Gi"
